### ISSUE TITLE
User is unable to sync with objkt.com via Safari

### ISSUE THREAD

**Issue by caseyalt** [bitmark-inc/autonomy-apps#1770] opened 2022-10-03 01:05 UTC
https://github.com/bitmark-inc/au-support-board/issues/569

**Comment by longbmk** [comment] 2022-10-03 05:02
https://github.com/bitmark-inc/autonomy-apps/issues/1771
I also logged the ticket but it is later than Casey ticket. So I will close it but please kindly notice the root cause is the application has not opened. I discuss with Hien about it. Thank you

**Comment by hvthhien** [comment] 2022-10-12 10:17
This should be fixed on the Web

**Comment by longbmk** [comment] 2023-02-23 04:13
This issue no longer happens

**Closed by longbmk** 2023-02-23 04:13 UTC
Labels: bug, 0.5 unit
